@startuml

Wort <|-- Rechtschreibtrainer

class Wort {
    -String wort
    -String url
    +Wort(String wort, String url)
    +getWort(): String
    +getUrl(): String
}

class Rechtschreibtrainer {
    -Wort[] woerter
    -Wort aktuellesWort
    -int insgesamtWorte
    -int richtigeWorte
    -int falscheWorte
    +wortWaehlen(): void
    +wortWaehlen(int index): void
    +raten(String wort): boolean
    +getAktuellesWort(): String
    +getUrl(): String
}

class GUI {
    -Controller controller
    -JPanel imagePanel
    +GUI()
    +updateImage(Wort wort): void
}

class Controller {
    -Rechtsschreibtrainer trainer
    -GUI gui
    +Controller()
    +check(String wort): void
    +getWort(): Wort
    +setGUI(GUI gui): void
}
@enduml